import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { NestSwaggerMetadataAdapter } from './nest-swagger-metadata.adapter';
import type { ResolvedOptions, ResolvedRoute } from '../types/options';
import type { NestControllerClass, NestSwaggerDecorators } from '../types/nest';

/** Adds rich OpenAPI metadata when `@nestjs/swagger` exists in the consuming app. */
export class NestSwaggerDecorator {
    private readonly swagger = NestSwaggerDecorator.load();

    decorateController(controller: NestControllerClass, options: ResolvedOptions): void {
        this.swagger?.ApiTags(options.model)(controller);
    }

    decorateOperation(
        target: object,
        propertyKey: string,
        descriptor: PropertyDescriptor,
        route: ResolvedRoute,
        method: string,
        options: ResolvedOptions,
    ): void {
        if (!this.swagger) return;

        const routeLabel = route.name === 'groupBy' ? 'Group' : NestSwaggerDecorator.title(route.name);
        const operationId = `${NestSwaggerDecorator.identifier(options.model)}_${route.name}_${method.toLowerCase()}`;

        this.swagger.ApiOperation({
            operationId,
            summary: `${routeLabel} ${options.model} records`,
        })(target, propertyKey, descriptor);
        this.swagger.ApiOkResponse({
            description: `${routeLabel} result generated by prisma-autoread`,
            schema: { type: 'object', additionalProperties: true },
        })(target, propertyKey, descriptor);
        this.swagger.ApiProduces(
            'application/hal+json',
            'application/json',
            'application/vnd.api+json',
            'text/csv',
        )(target, propertyKey, descriptor);

        if (method === 'GET') this.decorateQuery(target, propertyKey, descriptor, options);
        if (method === 'POST' || method === 'QUERY') {
            this.swagger.ApiBody({
                required: false,
                description: 'Prisma-shaped read query',
                schema: { type: 'object', additionalProperties: true },
            })(target, propertyKey, descriptor);
        }
    }

    private decorateQuery(
        target: object,
        propertyKey: string,
        descriptor: PropertyDescriptor,
        options: ResolvedOptions,
    ): void {
        const query = this.swagger!.ApiQuery;
        const keywords = options.keywords;
        const stringParameters = [
            keywords.sort,
            keywords.fields,
            keywords.include,
            keywords.search,
            keywords.distinct,
            keywords.cursor,
            keywords.format,
            keywords.count,
            keywords.sum,
            keywords.avg,
            keywords.min,
            keywords.max,
            keywords.by,
        ];

        query({
            name: keywords.filter,
            required: false,
            description: 'Prisma-style filter (deep-object bracket syntax)',
            style: 'deepObject',
            explode: true,
            schema: { type: 'object', additionalProperties: true },
        })(target, propertyKey, descriptor);
        query({
            name: keywords.having,
            required: false,
            description: 'Group-by HAVING filter (deep-object bracket syntax)',
            style: 'deepObject',
            explode: true,
            schema: { type: 'object', additionalProperties: true },
        })(target, propertyKey, descriptor);

        for (const name of stringParameters) {
            query({ name, required: false, schema: { type: 'string' } })(target, propertyKey, descriptor);
        }
        for (const name of [keywords.page, keywords.limit]) {
            query({ name, required: false, schema: { type: 'integer', minimum: 1 } })(
                target,
                propertyKey,
                descriptor,
            );
        }
    }

    private static load(): NestSwaggerDecorators | undefined {
        const requireFromApp = createRequire(resolve(process.cwd(), 'package.json'));

        try {
            requireFromApp.resolve('@nestjs/swagger/package.json');
        } catch (error) {
            const code = (error as { code?: string }).code;
            if (code === 'MODULE_NOT_FOUND' || code === 'ERR_MODULE_NOT_FOUND') return undefined;
            throw error;
        }

        try {
            return requireFromApp('@nestjs/swagger') as NestSwaggerDecorators;
        } catch (error) {
            const code = (error as { code?: string }).code;
            if (code === 'ERR_REQUIRE_ESM') return NestSwaggerMetadataAdapter.decorators();
            throw error;
        }
    }

    private static title(value: string): string {
        return value.charAt(0).toUpperCase() + value.slice(1);
    }

    private static identifier(value: string): string {
        return value.replace(/[^A-Za-z0-9_$]/g, '_');
    }
}
